/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class infoasys_cli_pangenes_PangeneNative */

#ifndef _Included_infoasys_cli_pangenes_PangeneNative
#define _Included_infoasys_cli_pangenes_PangeneNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     infoasys_cli_pangenes_PangeneNative
 * Method:    initialize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_infoasys_cli_pangenes_PangeneNative_initialize
  (JNIEnv *, jobject, jint);

/*
 * Class:     infoasys_cli_pangenes_PangeneNative
 * Method:    preprocessSequences
 * Signature: (Linfoasys/cli/pangenes/PangeneIData;)V
 */
JNIEXPORT void JNICALL Java_infoasys_cli_pangenes_PangeneNative_preprocessSequences
  (JNIEnv *, jobject, jobject);

/*
 * Class:     infoasys_cli_pangenes_PangeneNative
 * Method:    computePair
 * Signature: ([I[I)J
 */
JNIEXPORT jlong JNICALL Java_infoasys_cli_pangenes_PangeneNative_computePair
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     infoasys_cli_pangenes_PangeneNative
 * Method:    computeSequenceScores
 * Signature: (JIILinfoasys/cli/pangenes/PairScores;)V
 */
JNIEXPORT void JNICALL Java_infoasys_cli_pangenes_PangeneNative_computeSequenceScores
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     infoasys_cli_pangenes_PangeneNative
 * Method:    freePairStruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_infoasys_cli_pangenes_PangeneNative_freePairStruct
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
