/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class infoasys_cli_pangenes_PangeneNative_PairInfo */

#ifndef _Included_infoasys_cli_pangenes_PangeneNative_PairInfo
#define _Included_infoasys_cli_pangenes_PangeneNative_PairInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
