/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class infoasys_cli_pangenes_PangeneNative */

#ifndef _Included_infoasys_cli_pangenes_PangeneNative
#define _Included_infoasys_cli_pangenes_PangeneNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     infoasys_cli_pangenes_PangeneNative
 * Method:    initialize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_infoasys_cli_pangenes_PangeneNative_initialize
  (JNIEnv *, jobject, jint);

/*
 * Class:     infoasys_cli_pangenes_PangeneNative
 * Method:    preprocessSequences
 * Signature: (Linfoasys/cli/pangenes/PangeneIData;)V
 */
JNIEXPORT void JNICALL Java_infoasys_cli_pangenes_PangeneNative_preprocessSequences
  (JNIEnv *, jobject, jobject);

/*
 * Class:     infoasys_cli_pangenes_PangeneNative
 * Method:    computeScores
 * Signature: (ILinfoasys/cli/pangenes/Scores;)V
 */
JNIEXPORT void JNICALL Java_infoasys_cli_pangenes_PangeneNative_computeScores
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
