/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class infoasys_cli_pangenes_PangeneNative */

#ifndef _Included_infoasys_cli_pangenes_PangeneNative
#define _Included_infoasys_cli_pangenes_PangeneNative
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     infoasys_cli_pangenes_PangeneNative
 * Method:    preprocessSequences
 * Signature: (Linfoasys/cli/pangenes/PangeneIData;)V
 */
JNIEXPORT void JNICALL Java_infoasys_cli_pangenes_PangeneNative_preprocessSequences
        (JNIEnv *, jobject, jobject, jint, jboolean);

/*
 * Class:     infoasys_cli_pangenes_PangeneNative
 * Method:    computeScores
 * Signature: (IILinfoasys/cli/pangenes/Scores;)V
 */
JNIEXPORT void JNICALL Java_infoasys_cli_pangenes_PangeneNative_computeScores
        (JNIEnv *, jobject, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
